viewPath: './views'
servicePath: './src/services'
commonFilePath: './files'
port: 15001
secret: 'brokun'


staticServer:
 maxage: 5000
 hidden: false
 index: 'index.html'

token:
  ctxKey: 'user'
  tokenExp: 60 #minutes
  tokenLongExp: 90 #minutes
  tokenRolling:
   - 30
   - 'minutes'

session:
  sessionAge: 30 #minute
  option:
    prefix: 'online:'

redisStore:
 redis:
  host: 127.0.0.1
  port: 6379
  password: 'hzzh2017'
